name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'Formula/**'
      - '.gitattributes'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'README.md'
      - '.editorconfig'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'Formula/**'
      - '.gitattributes'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'README.md'
      - '.editorconfig'
      - 'LICENSE'

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Build
      run: go build -v ./...

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Lint
      uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
      with:
        version: v1.64

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Test
      run: go test -v -covermode=atomic ./...
